[project]
name = "KYC-as-a-Service"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/KYC-as-a-Service/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.KYC-as-a-Service]
path = "contracts/KYC-as-a-Service.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
